#!/usr/bin/env python3
"""Write urdf/so101_arm.xacro from the SO-101 URDF vendored in cad/.

The arm part of TheRobotStudio's so101_new_calib.urdf is copied number for
number. What changes:

  * the stock gripper goes: the gripper servo, the fixed and moving jaws, the
    `gripper` joint and gripper_frame_link. The scanner head bolts to the
    wrist-roll horn instead (urdf/scan_head.xacro);
  * gripper_link, the link the wrist_roll joint turns, is renamed
    wrist_roll_link, since nothing on it grips any more;
  * mesh paths point at package://so101_scan_description/meshes/so101/, where
    CMakeLists.txt installs the meshes from cad/vendor/so101/assets;
  * the ROS1 <transmission> blocks go; urdf/so101_scan.ros2_control.xacro
    says how the joints are driven.

Run it again only if cad/vendor/so101/so101_new_calib.urdf changes:

    python3 ros2/so101_scan_description/scripts/so101_urdf_to_xacro.py

test/test_description.py fails when the committed file is out of date.
"""

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
PKG = HERE.parent
REPO = PKG.parent.parent
URDF = REPO / "cad" / "vendor" / "so101" / "so101_new_calib.urdf"
OUT = PKG / "urdf" / "so101_arm.xacro"

ARM_LINKS = ["base_link", "shoulder_link", "upper_arm_link", "lower_arm_link", "wrist_link", "gripper_link"]
ARM_JOINTS = ["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll"]
RENAME = {"gripper_link": "wrist_roll_link"}
MESH_URI = "package://so101_scan_description/meshes/so101/"


def _origin(el, indent):
    o = el.find("origin")
    if o is None:
        return []
    return ['%s<origin xyz="%s" rpy="%s"/>' % (indent, o.get("xyz", "0 0 0"), o.get("rpy", "0 0 0"))]


def _geometry(el, indent):
    mesh = el.find("geometry/mesh")
    name = Path(mesh.get("filename")).name
    return ["%s<geometry>" % indent,
            '%s  <mesh filename="%s%s"/>' % (indent, MESH_URI, name),
            "%s</geometry>" % indent]


def link_xml(link):
    name = RENAME.get(link.get("name"), link.get("name"))
    out = ['    <link name="%s">' % name]
    if name != link.get("name"):
        out.append("      <!-- gripper_link in TheRobotStudio's URDF; the stock gripper parts on it are left out -->")
        out.append("    </link>")
        return out
    inertial = link.find("inertial")
    if inertial is not None:
        m = inertial.find("mass").get("value")
        i = inertial.find("inertia").attrib
        out += ["      <inertial>"] + _origin(inertial, "        ") + [
            '        <mass value="%s"/>' % m,
            '        <inertia ixx="%s" ixy="%s" ixz="%s" iyy="%s" iyz="%s" izz="%s"/>'
            % tuple(i[k] for k in ("ixx", "ixy", "ixz", "iyy", "iyz", "izz")),
            "      </inertial>"]
    for v in link.findall("visual"):
        mat = v.find("material")
        out += ["      <visual>"] + _origin(v, "        ") + _geometry(v, "        ")
        if mat is not None:
            out.append('        <material name="so101_%s"/>' % mat.get("name"))
        out.append("      </visual>")
    for c in link.findall("collision"):
        out += ["      <collision>"] + _origin(c, "        ") + _geometry(c, "        ") + ["      </collision>"]
    out.append("    </link>")
    return out


def joint_xml(joint):
    lim = joint.find("limit").attrib
    parent = joint.find("parent").get("link")
    child = joint.find("child").get("link")
    out = ['    <joint name="%s" type="%s">' % (joint.get("name"), joint.get("type"))]
    out += _origin(joint, "      ")
    out.append('      <parent link="%s"/>' % RENAME.get(parent, parent))
    out.append('      <child link="%s"/>' % RENAME.get(child, child))
    out.append('      <axis xyz="%s"/>' % joint.find("axis").get("xyz"))
    out.append('      <limit effort="%s" velocity="%s" lower="%s" upper="%s"/>'
               % (lim["effort"], lim["velocity"], lim["lower"], lim["upper"]))
    out.append("    </joint>")
    return out


def materials(root):
    out = []
    for m in root.findall("material"):
        out.append('  <material name="so101_%s">' % m.get("name"))
        out.append('    <color rgba="%s"/>' % m.find("color").get("rgba"))
        out.append("  </material>")
    return out


def generate(urdf=URDF):
    root = ET.parse(urdf).getroot()
    links = {ln.get("name"): ln for ln in root.findall("link")}
    joints = {j.get("name"): j for j in root.findall("joint")}
    lines = [
        '<?xml version="1.0"?>',
        "<!-- Generated by scripts/so101_urdf_to_xacro.py from cad/vendor/so101/so101_new_calib.urdf",
        "     (TheRobotStudio/SO-ARM100, Simulation/SO101, Apache-2.0). Do not edit by hand.",
        "     Joint zero is the URDF zero: upper arm straight up, forearm level, wrist in line. -->",
        '<robot xmlns:xacro="http://www.ros.org/wiki/xacro">',
    ]
    lines += materials(root)
    lines += ["", '  <xacro:macro name="so101_arm">']
    for name in ARM_LINKS:
        lines += link_xml(links[name])
    # parents before children, the way the arm is built
    for name in ARM_JOINTS:
        lines += joint_xml(joints[name])
    lines += ["  </xacro:macro>", "</robot>", ""]
    return "\n".join(lines)


def main():
    text = generate()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text() == text
        print("up to date" if ok else "%s is out of date; run %s" % (OUT, Path(__file__).name))
        return 0 if ok else 1
    OUT.write_text(text)
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
